version: "3.8"
services:
    mariadb:
        image: mariadb:latest
        container_name: mariadb
        command: --default-authentication-plugin=mysql_native_password
        restart: unless-stopped
        environment:
            MYSQL_ROOT_PASSWORD: admin
        volumes:
            - dbdata:/var/lib/mysql
        ports:
            - '3306:3306'

    phpmyadmin:
        image: phpmyadmin/phpmyadmin:latest
        container_name: phpmyadmin
        ports:
            - "8082:80"
        environment:
            MYSQL_ROOT_PASSWORD: admin
            PMA_HOST: mariadb
            PMA_USER: root
            PMA_PASSWORD: admin
   
volumes:
    dbdata: 
